### ISSUE TITLE
Passar o banco de dados para uma nuvem que fique online 24h

### ISSUE THREAD

**Issue by Hoffmano** [Hoffmano/reserva-academia#13]

**Comment by Hoffmano** [comment]
Acaba atrasando um pouco o desenvolvimente o fato de o banco de dados estar hospedado no servidor do @JoaoFukuda , pois nem sempre este está disponivel para testes.

**Comment by JoaoFukuda** [comment]
Eu criei um banco de dados no [ElephantSQL](https://www.elephantsql.com/) e vou agora migrar os dados do banco de dados antigo para o novo, @Hoffmano. Precisa ver se tem que mudar alguma coisa porque a gente estava usando MariaDB e agora estamos usando PostgreSQL.

**Comment by JoaoFukuda** [comment]
Quando eu passar todas as informações eu configuro o código para permitir credenciais externas, crio o documento e envio para você.

Eu vou fazer a inserção dos dados da maneira segura no github agora e excluir aquele banco de dados e o usuário antigos uma vez que terminar isso...

**Comment by JoaoFukuda** [comment]
Eu to fazendo a transferência com o [Python MySQL to PostgreSQL](https://github.com/philipsoutham/py-mysql2pgsql), mas está dando [esse erro aqui](https://github.com/philipsoutham/py-mysql2pgsql/issues/96). Precisa atualizar o banco de dados para ter um valor padrão na tabela como diz no issue. Conseguem fazer isso, @Hoffmano ou @15483114?

**Comment by JoaoFukuda** [comment]
eu tentei, mas não consegui.
O erro mudou, mas ainda não foi resolvido.

Agora o problema era que o *constraint* de chave externa do `reserva_sala` não estava apontando para uma exata sala.

O erro:
```
psycopg2.errors.InvalidForeignKey: there is no unique constraint matching given keys for referenced table "reserva_aula"
```
