### ISSUE TITLE
sistema de login

### ISSUE THREAD

**Issue by Hoffmano** [Hoffmano/reserva-academia#9]
- Usar os coockies capturados pelo request

**Comment by JoaoFukuda** [comment]
O sistema de login já está definido. Agora só faltam as credenciais (#12) para fazer um login funcional.
Quais são as funcionalidades só acessíveis enquanto logado e quais precisam de acesso superior (algo que um usuário comum não conseguiria acessar)?

**Comment by JoaoFukuda** [comment]
Ainda faltam definir as funcionalidades enquanto logado e se a gente vai usar admin ou não...
@Hoffmano e @15483114

**Comment by JoaoFukuda** [comment]
Agora falta só fazer com calma os diferentes casos de erro por falta de privilégio. Ta tudo muito generalisado
